# Generated by Django 5.2.1 on 2025-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="marks",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
